# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/klaasie/questionnaire/models/category/fields.yaml

# Model Class name
modelClass: Klaasie\Questionnaire\Models\Category

# Default redirect location
defaultRedirect: klaasie/questionnaire/categories

# Create page
create:
    title: Create Category
    redirect: klaasie/questionnaire/categories/update/:id
    redirectClose: klaasie/questionnaire/categories

# Update page
update:
    title: Edit Category
    redirect: klaasie/questionnaire/categories
    redirectClose: klaasie/questionnaire/categories

# Preview page
preview:
    title: Preview Category